# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Development Branches

on:
  push:
    branches: 
      - 'development/**'
    paths-ignore:
      - '.dockerignore'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches: 
      - 'development/**'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs global packages
        run: npm i -g eslint jest
      - name: Install dependencies
        run: npm i
      - name: Runs all tests with Jest
        run: npm run test
