# Worklow to update Nino Edge, development bot for testing the edge branch

name: Update Edge instance
on:
  push:
    branches:
      - edge
    paths-ignore:
      - '.dockerignore'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js v15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install global packages
        run: npm i -g eslint jest typescript

      - name: Install local packages
        run: npm ci

      - name: Run the linter
        run: npm run lint

      - name: Build the project for any errors
        run: tsc --noEmit

      - name: Run tests with Jest
        run: jest --config jest.config.js --forceExit

      - name: Push to Docker registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: registry.floofy.dev
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          tags: registry.floofy.dev/nino:edge
