name: ktlint
on:
  push:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master
      - edge

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'

  pull_request:
    branches:
      - 'feature/**'
      - 'issue/gh-**'
      - master
      - edge

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
jobs:
  ktlint:
    runs-on: ubuntu-latest
    services:
      redis:
        image: bitnami/redis:latest
        ports:
          - 6379:6379
      timeouts:
        image: ghcr.io/ninodiscord/timeouts/timeouts:latest
        env:
          AUTH: owodauwu
          REDIS_HOST: redis
          REDIS_PORT: 6379
        ports:
          - 4025:4025
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2

      - name: Sets up Java 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt # AdoptOpenJDK is <3
          java-version: 16

      - name: Setup gradle cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-test-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-test-gradle-

      - name: Lets ./gradlew be executable
        run: chmod +x ./gradlew

      - name: Lints the repository for any code errors
        run: ./gradlew spotlessCheck

      - name: Builds the project for any errors
        run: ./gradlew compileKotlin
