name: Lint the repository, test with Jest, and update the Discord bot (Master)
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs global packages
        run: npm i -g eslint jest
      - name: Install dependencies
        run: npm i
      - name: Lints the repository
        run: npm run lint
      - name: Runs all tests with Jest
        run: npm run test
      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/nino-prod
            git pull
            rm -fr node_modules
            rm yarn.lock
            yarn
            yarn build
            pm2 restart nino
