name: ESLint Workflow
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  shortlinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run the shortlinks script
        working-directory: .actions/build
        run: node shortlinks.js
