name: Lint the repository and test with Jest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 11.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs global packages
        run: npm i -g eslint jest
      - name: Install dependencies
        run: npm i
      - name: Lints the repository
        run: npm run lint
      - name: Runs all tests with Jest
        run: npm run test