name: Updates the Discord bot (Nino Edge)
on:
  push:
    branches:
      - edge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/nino-edge
            git pull
            yarn build
            pm2 restart "Nino Edge"